### ISSUE TITLE
Set Poster Image

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/jumbotron#2]
One feature I'd love to have is the ability to set the poster image from a frame of the video. There was a plugin back before blocks that I used and it worked really well. I wish I could remember the name of it. 

This is sorta related to the large image view. What I think riyvt does is instead of loading the actual video in the gallery view they just load the "poster" image along with a sort of fake play button and when clicked opens up the actual video in a lightbox. 

Daniel actually created a plugin that does something similar for YouTube videos:
https://lazy-embeds.com/

**Comment by nickhamze** [comment]
I don't know if something like this would help:
https://github.com/FinnovateIo/simple-react-video-thumbnail#readme

**Comment by Mamaduka** [comment]
Hi Nick,

To generate a video poster from the frame we've to write our custom API in PHP. Mostly to pass CORS requirements. Main problem with similar API is that you've to guess the frame.

There's an API for YouTube / Vimeo videos and this is what Riyvt and Lazy Embeds plugin are using.

We can probably provide a way for users to upload posters like core video blocks. But what happens in cases when some videos don't have posters, do we still provide lightbox functionality for them?
