### ISSUE TITLE
Video information

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/jumbotron#3]
Which pieces of the video information do you think it makes sense to add? At a minimum we should probably support either the caption or description since they are both in the core media uploader UI and they would be handy if you have tons of videos in a gallery to help people know what they are looking at.

**Comment by nickhamze** [comment]
If duration is easy to include that might be nice as well.

**Comment by Mamaduka** [comment]
@nickhamze 

Do we want to provide the ability to edit captions in the gallery block, as the image gallery does?
