### ISSUE TITLE
Add support for manual poster image

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/jumbotron#4]
@Mamaduka In the Media tab there is a "Featured Image" setting and when you set an image there it is used as the poster image. We don't currently support that feature. Would it be possible to add it?

<img width="1269" alt="Screen Shot 2020-02-26 at 10 31 34 AM" src="https://user-images.githubusercontent.com/158918/75365788-4df3ba00-5883-11ea-89a9-cc795cd6a6f5.png">

**Comment by Mamaduka** [comment]
Updated the code to support poster images.

**Comment by nickhamze** [comment]
@Mamaduka this all looks good. I think we are ok to push the new version.

**Comment by Mamaduka** [comment]
Created a new release. Should be deployed in WP.org in few minutes.
