### ISSUE TITLE
Difference between descriptions

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/jumbotron#5]
@Mamaduka For the descriptions is it possible to support the one in the media tab instead of the one in the media uploader? The one in the media tab supports HTML and is easier to use.

Also I added the secrets to the plugin if you wanted to set up the Github actions.

<img width="975" alt="Screen Shot 2020-02-26 at 10 34 23 AM" src="https://user-images.githubusercontent.com/158918/75366011-b3e04180-5883-11ea-87b1-ad5864c55f5b.png">

**Comment by Mamaduka** [comment]
Generally, I would avoid using HTML there, but I can update block so it supports it.

If the media already has a description, the block will grab that description when adding it. So actually there's no difference except nice HTML toolbar.

**Comment by nickhamze** [comment]
For some reason when I add a description via the Media interface it doesn't show up nor does it carry over the the video when I visit the page. However, if you allow HTML to the other description box that would be ok.

Someday it would be awesome if the description box showed up in the actual block on the backend and we could edit it like a block and the description was automatically saved back to the video.

**Comment by Mamaduka** [comment]
Descriptions should support HTML now.

**Comment by nickhamze** [comment]
@Mamaduka I'm really sorry about this but I was in a hurry and didn't test this very well. On the backend everything looks fine.
<img width="1440" alt="Screen Shot 2020-02-26 at 12 19 44 PM" src="https://user-images.githubusercontent.com/158918/75374732-6cad7d00-5892-11ea-8170-2e14a410cffa.png">

But on the front end it shows the HTML tags:
<img width="1047" alt="Screen Shot 2020-02-26 at 12 20 14 PM" src="https://user-images.githubusercontent.com/158918/75374780-7d5df300-5892-11ea-9787-91f8fd054457.png">

**Comment by Mamaduka** [comment]
Can you test it now? A small part of the logic was removed during poster feature update :(

**Comment by nickhamze** [comment]
Yeah that works now.

**Comment by Mamaduka** [comment]
So push minor release with a bug fix?

**Comment by nickhamze** [comment]
Yeah, probably have to.

**Comment by Mamaduka** [comment]
Done ✅
