### ISSUE TITLE
Something seems broken.

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/jumbotron#6]
@Mamaduka In 5.4 I see this on the backend and Null on the frontend. No idea why.

<img width="656" alt="Screen Shot 2020-03-25 at 5 21 15 PM" src="https://user-images.githubusercontent.com/158918/77591029-1f3a2500-6ebd-11ea-9b63-b0082628bad2.png">

Also it looks like we are missing the block description:
<img width="276" alt="Screen Shot 2020-03-25 at 5 22 46 PM" src="https://user-images.githubusercontent.com/158918/77591098-42fd6b00-6ebd-11ea-8c9e-d9f35bd3a768.png">

**Comment by Mamaduka** [comment]
@nickhamze I'm not able to reproduce the first issue. Tested on WP 5.3.2 and 5.4 latest RC.

**Comment by nickhamze** [comment]
@Mamaduka now I can't either. I guess it's ok. Bump and push.
